# Generated by Django 6.0.2 on 2026-03-06 16:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('doc_type', models.CharField(choices=[('receipt', 'Receipt'), ('invoice', 'Invoice'), ('quote', 'Quote'), ('credit_note', 'Credit Note'), ('delivery_note', 'Delivery Note'), ('custom', 'Custom')], default='receipt', max_length=20, verbose_name='Document Type')),
                ('paper_size', models.CharField(choices=[('thermal_80mm', 'Thermal 80mm'), ('thermal_58mm', 'Thermal 58mm'), ('a4', 'A4'), ('a5', 'A5'), ('letter', 'Letter')], default='thermal_80mm', max_length=20, verbose_name='Paper Size')),
                ('content', models.TextField(help_text='Template content with variable placeholders {{variable}}', verbose_name='Content')),
                ('header_content', models.TextField(blank=True, default='', verbose_name='Header Content')),
                ('footer_content', models.TextField(blank=True, default='', verbose_name='Footer Content')),
                ('css_styles', models.TextField(blank=True, default='', help_text='Custom CSS for this template', verbose_name='CSS Styles')),
                ('is_default', models.BooleanField(default=False, verbose_name='Is Default')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='Version')),
            ],
            options={
                'verbose_name': 'Document Template',
                'verbose_name_plural': 'Document Templates',
                'db_table': 'doc_templates_template',
                'ordering': ['doc_type', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateVariable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('name', models.CharField(help_text='Variable name e.g. {{sale.total}}', max_length=100, verbose_name='Name')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('variable_group', models.CharField(choices=[('sale', 'Sale'), ('invoice', 'Invoice'), ('customer', 'Customer'), ('product', 'Product'), ('company', 'Company'), ('custom', 'Custom')], default='custom', max_length=20, verbose_name='Group')),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('currency', 'Currency'), ('image', 'Image'), ('list', 'List')], default='text', max_length=20, verbose_name='Data Type')),
                ('example_value', models.CharField(blank=True, default='', max_length=255, verbose_name='Example Value')),
                ('is_system', models.BooleanField(default=True, help_text='System variables cannot be deleted', verbose_name='System Variable')),
            ],
            options={
                'verbose_name': 'Template Variable',
                'verbose_name_plural': 'Template Variables',
                'db_table': 'doc_templates_variable',
                'ordering': ['variable_group', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('doc_type', models.CharField(max_length=50, verbose_name='Document Type')),
                ('source_id', models.UUIDField(blank=True, help_text='ID of the source object (sale, invoice, etc.)', null=True, verbose_name='Source ID')),
                ('rendered_content', models.TextField(verbose_name='Rendered Content')),
                ('file', models.FileField(blank=True, null=True, upload_to='doc_templates/generated/', verbose_name='File')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='Generated At')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_documents', to='doc_templates.documenttemplate', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Generated Document',
                'verbose_name_plural': 'Generated Documents',
                'db_table': 'doc_templates_generated',
                'ordering': ['-generated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TemplateSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hub_id', models.UUIDField(blank=True, db_index=True, editable=False, help_text='Hub this record belongs to (for multi-tenancy)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.UUIDField(blank=True, help_text='UUID of the user who created this record', null=True)),
                ('updated_by', models.UUIDField(blank=True, help_text='UUID of the user who last updated this record', null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Soft delete flag - record is hidden but not removed')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True)),
                ('default_paper_size', models.CharField(choices=[('thermal_80mm', 'Thermal 80mm'), ('thermal_58mm', 'Thermal 58mm'), ('a4', 'A4'), ('a5', 'A5'), ('letter', 'Letter')], default='thermal_80mm', max_length=20, verbose_name='Default Paper Size')),
                ('default_font_size', models.IntegerField(default=12, verbose_name='Default Font Size')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='doc_templates/logos/', verbose_name='Company Logo')),
                ('company_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Company Name')),
                ('company_address', models.TextField(blank=True, default='', verbose_name='Company Address')),
                ('company_tax_id', models.CharField(blank=True, default='', max_length=50, verbose_name='Tax ID')),
                ('company_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Phone')),
                ('company_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('company_website', models.URLField(blank=True, default='', verbose_name='Website')),
                ('footer_text', models.TextField(blank=True, default='', verbose_name='Footer Text')),
            ],
            options={
                'verbose_name': 'Template Settings',
                'verbose_name_plural': 'Template Settings',
                'db_table': 'doc_templates_settings',
                'abstract': False,
                'unique_together': {('hub_id',)},
            },
        ),
    ]
